source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'CCFreshStoreApp' do
	#Objective-C
	pod 'AFNetworking', '~> 3.1.0'
	pod 'FMDB', '~> 2.7.2'
	pod 'Masonry', '~> 1.1.0'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'MJRefresh', '~> 3.1.15'
	pod 'SDWebImage', '~> 4.2.1'
	pod 'TZImagePickerController', '~> 1.9.3'
	pod 'YYModel', '~> 1.0.4'
end
